#!/usr/bin/env bash

#client_ip="172.16.0.4"
#file_name="detail-$(date +%Y%m%d)"

#sudo tail -n100 ./volumes/log/radacct/$client_ip/$file_name

serviceName="$1"
cont_id=$(docker ps -a | grep $serviceName | awk -s '{ print $1 }')
#echo "Container ID: $cont_id"

cmd="$2"
echo "sudo docker exec -it $cont_id /bin/sh -c \"$2\""
#sudo docker exec -it $cont_id /bin/sh -c $2

#cont_id=$(sudo docker ps -a |grep -o [a-zA-Z0-9_-]*$serviceName[a-zA-Z0-9_-]*)
#cont_id="tacplus_tac_plus_1"
#echo $cont_id

#echo "sudo docker logs $cont_id -f"
#sudo docker logs $cont_id -f

#echo "Testing container $serviceName"
#echo
#echo "Ping test $serviceName -> ospf neighbor"
#echo "sudo docker -it $cont_id /bin/sh -c \"ping -c 3 192.168.3.20\""
#sudo docker exec -it $cont_id /bin/sh -c "ping -c 3 192.168.3.20"
#
#exit
