#!/usr/bin/env bash

element=$1

if [ $element == "all" ];then
  element=casa
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  sudo docker exec -it $cont_name /bin/ash -c "birdc configure"
  element="isp1"
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  sudo docker exec -it $cont_name /bin/ash -c "birdc configure"
  element="isp2"
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  sudo docker exec -it $cont_name /bin/ash -c "birdc configure"
  element="isp3"
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  sudo docker exec -it $cont_name /bin/ash -c "birdc configure"
else
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  
  # reload bird configuration
  sudo docker exec -it $cont_name /bin/ash -c "birdc configure && birdc show protocol"
  
  # show protocol configuration
  #sudo docker exec -it bird_rg_1 /bin/ash -c "birdc show protocol all"
fi
