#!/usr/bin/env bash

#client_ip="172.16.0.4"
#file_name="detail-$(date +%Y%m%d)"

#sudo tail -n100 ./volumes/log/radacct/$client_ip/$file_name

[ $# -eq 0 ] && serviceName="ospf1" || serviceName="$1"

#serviceName="ospf1"

cont_name=$(docker ps -a | grep $serviceName | awk -s '{ print $1 }')

#cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_-]*$serviceName[a-zA-Z0-9_-]*)
#cont_name="tacplus_tac_plus_1"
#echo $cont_name

echo "sudo docker logs $cont_name -f"

sudo docker logs $cont_name -f

exit
