#!/usr/bin/env bash

#client_ip="172.16.0.4"
#file_name="detail-$(date +%Y%m%d)"

#sudo tail -n100 ./volumes/log/radacct/$client_ip/$file_name

serviceName="ospf1"

cont_id=$(docker ps -a | grep $serviceName | awk -s '{ print $1 }')

#cont_id=$(sudo docker ps -a |grep -o [a-zA-Z0-9_-]*$serviceName[a-zA-Z0-9_-]*)
#cont_id="tacplus_tac_plus_1"
#echo $cont_id

#echo "sudo docker logs $cont_id -f"
#sudo docker logs $cont_id -f

echo "Testing container $serviceName"
echo
echo "Testing IP connectivity ospf1 -> dn"

echo "Testing IP connectivity ospf1 -> msr"

echo "Ping test $serviceName -> ospf neighbor"
echo "sudo docker -it $cont_id /bin/sh -c \"ping -c 3 192.168.3.20\""
sudo docker exec -it $cont_id /bin/sh -c "ping -c 3 192.168.3.20"

exit
