#!/usr/bin/env bash

element=$1

#cont_name=$(sudo docker ps -a |grep $element |awk '{ print $14 }')
cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)

# reload bird configuration
#sudo docker exec -it $cont_name /bin/ash -c "birdc configure"

# show protocol configuration
sudo docker exec -it $cont_name /bin/ash -c "birdc show protocol all && birdc show protocols && birdc show route"
