#!/usr/bin/env bash

SERVICE_LIBRARY="ospf"
#DEBUG=true

# grab configuration
OSPF_SOURCE=${BASH_SOURCE[0]}
OSPF_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $OSPF_SCRIPT_DIR/../functions.sh

cd $OSPF_SCRIPT_DIR

# overwrite any eventually changed configuration
source $OSPF_SCRIPT_DIR/running.conf

bridge1Interface="$ospf1Interface.$ospf1InterfaceVlan"
bridge1Name="$ospf1BridgeName"
bridge2Interface="$ospf2Interface.$ospf2InterfaceVlan"
bridge2Name="$ospf2BridgeName"

#detach_bridge_interface
bridge_interface detach $bridge1Interface $bridge1Name
bridge_interface detach $bridge2Interface $bridge2Name
compose_down $SERVICE_LIBRARY
#remove_running_conf_file
rm_running_config

#sudo docker-compose -p routing -f compose.yaml down
