#!/usr/bin/env bash

#echo "Sourced functions.lib"

# grab configuration
FUNC_LIB_SOURCE=${BASH_SOURCE[0]}
FUNC_LIB_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $FUNC_LIB_SCRIPT_DIR/ancillary.conf

[ -z $DEBUG ] && DEBUG="FALSE"

#echo "SOURCE: $SOURCE"
#echo "SCRIPT_DIR: $SCRIPT_DIR"

# RADIUS specific library
aaa_library()
{
  # set interface type
  if [ $aaaInterfaceVlan = "0" ]; then
    aaaIf="$aaaInterface"
    isVlanIf="false"
  else
    aaaIf="$aaaInterface.$aaaInterfaceVlan"
    isVlanIf="true"
  fi
    
  aaaBS=$(echo $aaaBridgeSubnet | sed -e "s.\/.\\\/.g")

  # adds a physical interface to the radius bridge (for external reachability)
  attach_bridge_interface()
  {
    # create vlan interface, if necessary 
    if [ $(sudo ip link show | grep "$aaaIf" | wc -l) -lt 1 ]; then
      if [ $isVlanIf = "true" ]; then
        ipv4_to_lamac $aaa1IpAddress
        create_vlan_interface $aaaIf
      fi
    fi

    if [ $(sudo brctl show $aaaBridgeName |grep $aaaIf |wc -l) -gt 0 ]; then
      echo "Interface $aaaIf already assigned to bridge, nothing to do"
      sudo brctl show $aaaBridgeName |grep $aaaIf
      return
    elif [ $(sudo brctl show | grep $aaaIf |wc -l) -gt 0 ]; then
      echo "Interface $aaaIf assigned to another bridge, please remove interface first"
      return
    fi
  
    sudo ip link set dev $aaaIf master $aaaBridgeName
  }

  detach_bridge_interface()
  {
    if [ $(sudo brctl show $aaaBridgeName |grep $aaaIf |wc -l) -gt 0 ]; then 
      sudo ip link set dev $aaaInterface nomaster
    fi

    [ $isVlanIf = "true" ] && delete_vlan_interface $aaaIf

  }

  build_compose_file() {
    #echo $aaaBS
    cat $composeSampleFile | \
    sed -e "s/\$aaaBridgeName/$aaaBridgeName/g" \
      -e "s/\$aaa1IpAddress/$aaa1IpAddress/g" \
      -e "s/\$aaa2IpAddress/$aaa2IpAddress/g" \
      -e "s/\$aaaClientIpAddress/$aaaClientIpAddress/g" | \
      sed -e "s/\$aaaBridgeSubnet/$aaaBS/g" > $composeDestFile
    #cat $temp_yaml_file
  }

  build_configuration()
  {
    [ $DEBUG = "TRUE" ] && echo "${FUNCNAME[0]}"
    # authorize, clients.conf, testrun
    
    #owner=$(ls -l $authDestFile | awk '{ print $3":"$4 }')
    owner="root:systemd-journal"

    # authorize file
    [ $DEBUG = "TRUE" ] && echo "  Building $authDestFile"
    sudo chown $USER:$USER $authDestFile
    sudo cat $authTemplFile | \
      sed -e "s/\$aaaCasaVrfName/$aaaCasaVrfName/g" > $authDestFile
    #[ $DEBUG = "TRUE" ] && head $authDestFile
    sudo chown $owner $authDestFile

    # clients.conf file
    [ $DEBUG = "TRUE" ] && echo "  Building $clientsDestFile"
    sudo chown $USER:$USER $clientsDestFile
    [ $DEBUG = "TRUE" ] && echo "  Parameters: $aaaBridgeSubnet, $aaaSecret, $clientsDestFile"
    sudo cat $clientsTemplFile | \
      sed -e "s/\$aaaBridgeSubnet/$aaaBS/g" \
          -e "s/\$aaaSecret/$aaaSecret/g" > $clientsDestFile
    [ $DEBUG = "TRUE" ] && head $clientsDestFile
    sudo chown $owner $clientsDestFile
    
    # testrun file
    [ $DEBUG = "TRUE" ] && echo "  Building $testrunDestFile"
    #sudo chown $USER:$USER $testrunDestFile
    #[ $DEBUG = "TRUE" ] && echo "  Parameters: $aaaBridgeSubnet, $aaaSecret, $testrunDestFile"
    cat $testrunTemplFile | \
      sed -e "s/\$aaaSecret/$aaaSecret/g" \
          -e "s/\$aaa1IpAddress/$aaa1IpAddress/g" \
          -e "s/\$aaa2IpAddress/$aaa2IpAddress/g" > $testrunDestFile
    [ $DEBUG = "TRUE" ] && head $testrunDestFile
    #sudo chown $owner $testrunDestFile
  }

  remove_running_conf_file()
  {
    # remove old file
    if [ -e $AAA_SCRIPT_DIR/running.conf ]; then
      sudo chmod +w $AAA_SCRIPT_DIR/running.conf
      rm -f $AAA_SCRIPT_DIR/running.conf
    fi
  }

  write_running_config()
  {
    remove_running_conf_file
    echo "# RUNNING CONFIGURATION, DO NOT EDIT THIS FILE!!!" > $AAA_SCRIPT_DIR/running.conf
    cat $FUNC_LIB_SCRIPT_DIR/ancillary.conf >> $AAA_SCRIPT_DIR/running.conf

    # make it read-only
    sudo chmod 444 $AAA_SCRIPT_DIR/running.conf
  }
 
  clean_up_directory()
  {
    echo "Re-setting ownership to $USER:$USER"
    sudo chown -R $USER:$USER $AAA_SCRIPT_DIR/volumes
    
    echo "Deleting log files"
    sudo rm -r $AAA_SCRIPT_DIR/volumes/log/
  }

}

speedtest_library()
{
  # set interface type
  if [ $speedtestInterfaceVlan = "0" ]; then
    speedtestIf="$speedtestInterface"
    isVlanIf="false"
  else
    speedtestIf="$speedtestInterface.$speedtestInterfaceVlan"
    isVlanIf="true"
  fi

  # adds a physical interface to the radius bridge (for external reachability)
  attach_bridge_interface()
  {
    # create vlan interface, if necessary 
    if [ $(sudo ip link show | grep "$speedtestIf" | wc -l) -lt 1 ]; then
      if [ $isVlanIf = "true" ]; then
        ipv4_to_lamac $speedtestIpAddress
        create_vlan_interface $speedtestIf
      fi
    fi

    if [ $(sudo brctl show $speedtestBridgeName |grep $speedtestIf |wc -l) -gt 0 ]; then
      echo "Interface $speedtestIf already assigned to bridge, nothing to do"
      sudo brctl show $speedtestBridgeName |grep $speedtestIf
      return
    elif [ $(sudo brctl show | grep $speedtestIf |wc -l) -gt 0 ]; then
      echo "Interface $speedtestIf assigned to another bridge, please remove interface first"
      return
    fi
  
    sudo ip link set dev $speedtestIf master $speedtestBridgeName
  }

  detach_bridge_interface()
  {
    if [ $(sudo brctl show $speedtestBridgeName |grep $speedtestIf |wc -l) -gt 0 ]; then 
      sudo ip link set dev $speedtestIf nomaster
    fi

    [ $isVlanIf = "true" ] && delete_vlan_interface $speedtestIf
  }

  build_compose_file() 
  {
    stBS=$(echo $speedtestBridgeSubnet | sed -e "s.\/.\\\/.g")
    #echo $sttBS
    cat $composeSampleFile | \
    sed -e "s/\$speedtestBridgeName/$speedtestBridgeName/g" \
      -e "s/\$speedtestIpAddress/$speedtestIpAddress/g" \
      -e "s/\$speedtestBridgeSubnet/$stBS/g" > $composeDestFile
    #cat $temp_yaml_file
  }

  remove_running_conf_file()
  {
    # remove old file
    if [ -e $ST_SCRIPT_DIR/running.conf ]; then
      sudo chmod +w $ST_SCRIPT_DIR/running.conf
      rm -f $ST_SCRIPT_DIR/running.conf
    fi
  }

  write_running_config()
  {
    remove_running_conf_file

    echo "# RUNNING CONFIGURATION, DO NOT EDIT THIS FILE!!!" > $ST_SCRIPT_DIR/running.conf
    cat $FUNC_LIB_SCRIPT_DIR/ancillary.conf >> $ST_SCRIPT_DIR/running.conf

    # make it read-only
    sudo chmod 444 $ST_SCRIPT_DIR/running.conf
  }

  clean_up_directory()
  {
    echo "Deleting dynamic configuration files"
    sudo rm -r $ST_SCRIPT_DIR/config/
  }

}

bgp_library()
{
  [ $DEBUG = "TRUE" ] && echo "${FUNCNAME[0]}"

  # set interface type
  if [ $bgp1InterfaceVlan = "0" ]; then
    bgp1If="$bgp1Interface"
    bgp1isVlanIf="false"
  else
    bgp1If="$bgp1Interface.$bgp1InterfaceVlan"
    bgp1isVlanIf="true"
  fi
  [ $DEBUG = "TRUE" ] && echo "  bgp1If: $bgp1If"

  if [ $bgp2InterfaceVlan = "0" ]; then
    bgp2If="$bgp2Interface"
    bgp2isVlanIf="false"
  else
    bgp2If="$bgp2Interface.$bgp2InterfaceVlan"
    bgp2isVlanIf="true"
  fi
  [ $DEBUG = "TRUE" ] && echo "  bgp2If: $bgp2If"
    
  # adds a physical interfaces to a bgp bridge (for external reachability)
  attach_bridge_interface()
  {
  [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    # create vlan interface for first bgp connection (if necessary)
    if [ $(sudo ip link show | grep "$bgp1If" | wc -l) -lt 1 ]; then
      if [ $bgp1isVlanIf = "true" ]; then
        ipv4_to_lamac $bgp1IpAddress
        create_vlan_interface $bgp1If
      fi
    fi

    if [ $(sudo brctl show $bgp1BridgeName |grep $bgp1If |wc -l) -gt 0 ]; then
      echo "Interface $bgp1If already assigned to bridge, nothing to do"
      sudo brctl show $bgp1BridgeName |grep $bgp1If
      return
    elif [ $(sudo brctl show | grep $bgp1If |wc -l) -gt 0 ]; then
      echo "Interface $bgp1If assigned to another bridge, please remove interface first"
      return
    fi

    sudo ip link set dev $bgp1If master $bgp1BridgeName

    # create vlan interface for second bgp connection (if necessary)
    if [ $(sudo ip link show | grep "$bgp2If" | wc -l) -lt 1 ]; then
      if [ $bgp2isVlanIf = "true" ]; then
        ipv4_to_lamac $bgp2IpAddress
        create_vlan_interface $bgp2If
      fi
    fi

    if [ $(sudo brctl show $bgp2BridgeName |grep $bgp2If |wc -l) -gt 0 ]; then
      echo "Interface $bgp2If already assigned to bridge, nothing to do"
      sudo brctl show $bgp2BridgeName |grep $bgp2If
      return
    elif [ $(sudo brctl show | grep $bgp2If |wc -l) -gt 0 ]; then
      echo "Interface $bgp2If assigned to another bridge, please remove interface first"
      return
    fi
  
    sudo ip link set dev $bgp2If master $bgp2BridgeName
  }

  set_bridge_interface()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}" 
    [ $DEBUG = "TRUE" ] && echo "    isp: $1 action: $2"
    [ $DEBUG = "TRUE" ] && echo "    bgp1If: $bgp1If bgp2If: $bgp2If"
    isp=$1
    action=$2
    [ $isp = "isp1" ] && bridgeName=$bgp1BridgeName
    [ $isp = "isp2" ] && bridgeName=$bgp2BridgeName

    case $action in
      up)
        [ $DEBUG = "TRUE" ] && echo "    sudo ip link set dev $bridgeName up"
        sudo ip link set dev $bridgeName up
        ;;
      down)
        [ $DEBUG = "TRUE" ] && echo "    sudo ip link set dev $bridgeName down"
        sudo ip link set dev $bridgeName down
        ;;
      *)
        [ $DEBUG = "TRUE" ] && echo "    \"$action\" is no valid action!"
        exit
    esac

  }

  detach_bridge_interface()
  { 
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    if [ $(sudo brctl show $bgp1BridgeName |grep $bgp1If |wc -l) -gt 0 ]; then 
      sudo ip link set dev $bgp1Interface nomaster
    fi

    [ $bgp1isVlanIf = "true" ] && delete_vlan_interface $bgp1If

    if [ $(sudo brctl show $bgp2BridgeName |grep $bgp2If |wc -l) -gt 0 ]; then 
      sudo ip link set dev $bgp2Interface nomaster
    fi

    [ $bgp2isVlanIf = "true" ] && delete_vlan_interface $bgp2If

  }

  build_compose_file() 
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    bgp1BS=$(echo $bgp1BridgeSubnet | sed -e "s.\/.\\\/.g")
    bgp2BS=$(echo $bgp2BridgeSubnet | sed -e "s.\/.\\\/.g")
    [ $DEBUG = "TRUE" ] && echo "    bgp1BS: $bgp1BS"
    [ $DEBUG = "TRUE" ] && echo "    bgp2BS: $bgp2BS"

    cat $composeSampleFile | \
    sed -e "s/\$bgp1IpAddress/$bgp1IpAddress/g" \
      -e "s/\$bgp2IpAddress/$bgp2IpAddress/g" \
      -e "s/\$bgp1BridgeName/$bgp1BridgeName/g" \
      -e "s/\$bgp2BridgeName/$bgp2BridgeName/g" | \
      sed -e "s/\$bgp3BridgeName/$bgp3BridgeName/g" \
      -e "s/\$bgp4BridgeName/$bgp4BridgeName/g" \
      -e "s/\$bgp5BridgeName/$bgp5BridgeName/g" | \
      sed -e "s/\$bgp1BridgeSubnet/$bgp1BS/g" \
      -e "s/\$bgp2BridgeSubnet/$bgp2BS/g" > $composeDestFile
    
    [ $DEBUG = "TRUE" ] && echo "    created compose file $composeDestFile"
  }

  remove_running_conf_file()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    # remove old file
    if [ -e $BGP_SCRIPT_DIR/running.conf ]; then
      sudo chmod +w $BGP_SCRIPT_DIR/running.conf
      rm -f $BGP_SCRIPT_DIR/running.conf
    fi
  }

  write_running_config()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    remove_running_conf_file
    echo "# RUNNING CONFIGURATION, DO NOT EDIT THIS FILE!!!" > $BGP_SCRIPT_DIR/running.conf
    cat $FUNC_LIB_SCRIPT_DIR/ancillary.conf >> $BGP_SCRIPT_DIR/running.conf

    # make it read-only
    sudo chmod 444 $BGP_SCRIPT_DIR/running.conf
  }
 
  clean_up_directory()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    echo "Re-setting ownership to $USER:$USER"
    sudo chown -R $USER:$USER $BGP_SCRIPT_DIR/volumes
    
    echo "Deleting log files"
    sudo rm -r $BGP_SCRIPT_DIR/volumes/log/
  }

}

commons_library()
{
  [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
  compose_up()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    case $1 in
      aaa)
        sudo docker-compose -p radius -f compose.yaml up -d
        ;;
      speedtest)
        sudo docker-compose -p speedtest -f compose.yaml up -d
        ;;
      bgp)
        sudo docker-compose -p bgp -f compose.yaml up -d
        ;;
      *)
        return
        ;;
    esac
  }
    
  compose_down()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    case $1 in
      aaa)
        sudo docker-compose -p radius -f compose.yaml down
        ;;
      speedtest)
        sudo docker-compose -p speedtest -f compose.yaml down
        ;;
      bgp)
        sudo docker-compose -p bgp -f compose.yaml down
        ;;
      *)
        return
        ;;
    esac
  }
  create_vlan_interface()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    vlanInterface=$1
    ifId=$(echo $vlanInterface | sed -e 's/\./ /' | awk '{ print $1 }')
    vlanId=$(echo $vlanInterface | sed -e 's/\./ /' | awk '{ print $2 }')
    
    sudo ip link add link $ifId address $laMac name $vlanInterface type vlan id $vlanId 

    if [ $(sudo ip link show | grep "$vlanInterface" | wc -l) -lt 1 ]; then
      echo "create_vlan_interface: Failed creating vlan interface $vlanInterface, exiting"
      exit
    else
      sudo ip link set dev $ifId up
      sudo ip link set dev $vlanInterface up
    fi
  }

  delete_vlan_interface()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    vlanInterface=$1
    if [ $(sudo ip link show | grep "$vlanInterface" | wc -l) -gt 0 ]; then
      sudo ip link delete $vlanInterface
      if [ $(sudo ip link show | grep "$vlanInterface" | wc -l) -gt 0 ]; then
        echo "delete_vlan_interface: Failed deleting interface $vlanInterface"
      fi
    fi
  }

  ipv4_to_lamac()
  {
    [ $DEBUG = "TRUE" ] && echo "  ${FUNCNAME[0]}"
    ipv4Addr=$1
  
    oct1=$(echo $ipv4Addr | sed -e 's/\./ /g' | awk '{ print $1 }')
    oct2=$(echo $ipv4Addr | sed -e 's/\./ /g' | awk '{ print $2 }')
    oct3=$(echo $ipv4Addr | sed -e 's/\./ /g' | awk '{ print $3 }')
    oct4=$(echo $ipv4Addr | sed -e 's/\./ /g' | awk '{ print $4 }')

    [ $oct1 -lt 16 ] && mac1=$(printf '0%x\n' $oct1) || mac1=$(printf '%x\n' $oct1)
    [ $oct2 -lt 26 ] && mac2=$(printf '0%x\n' $oct2) || mac2=$(printf '%x\n' $oct2)
    [ $oct3 -lt 36 ] && mac3=$(printf '0%x\n' $oct3) || mac3=$(printf '%x\n' $oct3)
    [ $oct4 -lt 46 ] && mac4=$(printf '0%x\n' $oct4) || mac4=$(printf '%x\n' $oct4)

    laMac="02:00:$mac1:$mac2:$mac3:$mac4"
  }


  return
}

### main
case $SERVICE_LIBRARY in
  aaa)
    aaa_library
    ;;
  speedtest)
    speedtest_library
    ;;
  bgp)
    bgp_library
    ;;
  *) 
    echo "unknown service"
    ;;
esac

commons_library

## grab configuration file
##SOURCE=${BASH_SOURCE[0]}
##SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
##source $SCRIPT_DIR/config 
#
##site_name=$1
##yaml_template="$SCRIPT_DIR/jumphost.yaml"
##temp_yaml_file=${REMOTE_SITE}_temp.yaml
#
#load_config() {
#  echo "Loading configuration for site: $site_name"
#  $site_name
#  # echo "$IMAGE_VERSION $REMOTE_SITE $LAN_IP $LAN_IF"
#}
#
#build_tempfile () {
#  sed -e "s/\$LAN_IP/$LAN_IP/g" \
#      -e "s/\$LAN_IF/$LAN_IF/g" \
#      -e "s/\$REMOTE_SITE/$REMOTE_SITE/g" \
#      -e "s/\$IMAGE_VERSION/$IMAGE_VERSION/g" $yaml_template > $temp_yaml_file
#  #cat $temp_yaml_file
#}
#
#run_compose_up () {
#  yaml_filename=$1
#  sudo docker-compose -p jumphost -f $yaml_filename up -d
#  #cat $yaml_filename
#}
#
#run_compose_down () {
#  yaml_filename=$1
#  #cat $yaml_filename
#  sudo docker-compose -p jumphost -f $yaml_filename kill
#  sudo docker-compose -p jumphost -f $yaml_filename rm -f
#}
#
#interface_ip_add () {
#  # check if exist
#  if [ $(ip addr show dev $LAN_IF | grep "$LAN_IP" | wc -l) -gt 0 ]; then
#    echo "ip exist, no need to set up"
#  else
#    echo "set up IP: $LAN_IF ${LAN_IP}/${LAN_IP_PREFIX}"
#    sudo ip addr add ${LAN_IP}/${LAN_IP_PREFIX} dev $LAN_IF
#  fi
#}
#
#interface_ip_delete () {
#  if [ $(ip addr show dev $LAN_IF | grep "$LAN_IP" | wc -l) -gt 0 ]; then
#    echo "Remove ${LAN_IP}/${LAN_IP_PREFIX} from dev $LAN_IF "
#    sudo ip addr del ${LAN_IP}/${LAN_IP_PREFIX} dev $LAN_IF
#  else
#    echo "Remove IP: ${LAN_IP}/${LAN_IP_PREFIX} on dev $LAN_IF does not exsit, nothing to do"
#  fi
#}
#
#connect_to_container () {
#  ssh -o StrictHostKeyChecking=no \
#    -o GlobalKnownHostsFile=/dev/null \
#    -o UserKnownHostsFile=/dev/null \
#    -i ./rev-tunnel \
#    rxs@$LAN_IP \
#    -p 51000
#}
#
#get_ssh_revtunnel_id () {
#  sudo docker exec jumphost_edgehub_1 /bin/ps -efd | grep "rxs.*sshd:.*rxs" | awk '{ print $1 }'
#}
#
#get_container_id () {
#  sudo docker ps | grep "$site_name" | awk '{ print $1 }'
#}
#
#### MAIN
### check if configuration exist in configuration file
##if [ -n "$(type -t $site_name)" ] && [ "$(type -t $site_name)" = function ]; then
##  # site exists
##  load_config
##  build_tempfile
##  run_compose
##else
##  # site not round
##  echo "Can't find configuration for $site_name, check config file!"
##  exit
##fi
##
##echo "Ende"
##
###sudo docker-compose -p jumphost -f $yaml_filename up -d
