#!/bin/ash

shared_key=$aaaSecret
aaa_server_ip_1=$aaa1IpAddress
aaa_server_ip_2=$aaa2IpAddress
# original
#aaa_server_ip_1=172.16.0.2
#aaa_server_ip_2=172.16.0.3

BASE_DIR=$(dirname "$0")

AUTH="User-Name=testing, \
  User-Password=password, \
  NAS-IP-Address=10.0.0.1"

ACCT_START="Acct-Status-Type=Start, \
  Acct-Session-Id=\"testing\", \
  NAS-IP-Address=10.0.0.1, \
  Client-IP-Address=192.168.0.1, \
  Acct-Unique-Session-Id=\"123456789\""
  
ACCT_STOP="Acct-Status-Type=Stop, \
  Acct-Session-Id=\"testing\", \
  NAS-IP-Address=10.0.0.1, \
  Client-IP-Address=192.168.0.1, \
  Acct-Unique-Session-Id=\"123456789\""

COA="User-Name= 00:00:28:10:05:01, \
  NAS-IP-Address=172.16.0.15"

test_sequence()
{
  sleep 1
  #radclient -f $BASE_DIR/auth -c 1 -r 2 -t 1 -x $aaa_server_ip auth $shared_key
  echo "$AUTH" | radclient -c 1 -r 2 -t 1 -x $aaa_server_ip auth $shared_key

  #sleep 1
  #radclient -f $BASE_DIR/acct-start -c 1 -r 2 -t 1 -x $aaa_server_ip acct $shared_key
  echo "$ACCT_START" | radclient -c 1 -r 2 -t 1 -x $aaa_server_ip acct $shared_key

  #sleep 1
  #radclient -f $BASE_DIR/acct-stop -c 1 -r 2 -t 1 -x $aaa_server_ip acct $shared_key
  echo "$ACCT_STOP" | radclient -c 1 -r 2 -t 1 -x $aaa_server_ip acct $shared_key
}

aaa_server_ip=$aaa_server_ip_1
test_sequence

aaa_server_ip=$aaa_server_ip_2
test_sequence
