---
version: "2.1"
services:
  speedtest:
    image: rsattler/speedtest
    container_name: speedtest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false #optional
      #- DB_TYPE=sqlite #optional
      #- DB_NAME=DB_NAME #optional
      #- DB_HOSTNAME=DB_HOSTNAME #optional
      #- DB_USERNAME=DB_USERNAME #optional
      #- DB_PASSWORD=DB_PASSWORD #optional
      #- DB_PORT=DB_PORT #optional
    volumes:
      - ./config:/config
    networks:
      speedt_net:
        ipv4_address: $speedtestIpAddress
    restart: unless-stopped

networks:
  speedt_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: $speedtestBridgeName
    ipam:
      driver: default
      config:
        - subnet: $speedtestBridgeSubnet
