#!/usr/bin/env ash

source /tmp/customize/running.conf

# grep prefix
ospf2Ipv6Prefix=$(echo "$ospf2v6BridgeSubnet" | sed -e 's/^.*\//\//')

# configuration parameters

# loopback interface
lo_name=lo10
lo_ip=10.255.254.40/32
lo_ipv6=fd00::10:255:254:40/128

eth0_ipv6="$ospf2Ipv6Address$ospf2Ipv6Prefix"
eth1_ipv6="fd00::11:0:2:40/112"
#eth1_link="fe80::11:20:0:10/64"

