version: '3'

#- /home/ralf/docker/bird-routing/bgp_sample/volumes:/tmp/volumes:ro
# sudo docker run -d  -p 55022:22 --name bird1 bird
services:
  tac_plus:
    image: rsattler/tacacs_plus
    ports:
      - "49:49"
    networks:
      tacPlus_net:
        ipv4_address: 172.16.2.13
    volumes:
      - ./volumes/log/:/var/log/tac_plus/
      - ./volumes/customize/:/etc/tac_plus/
    cap_add:
      - NET_ADMIN

networks:
  tacPlus_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: tac_plus
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
