#!/usr/bin/env bash

SERVICE_LIBRARY="tacplus"
DEBUG=true

# grab configuration
TACP_SOURCE=${BASH_SOURCE[0]}
TACP_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $TACP_SCRIPT_DIR/../functions.sh

cd $TACP_SCRIPT_DIR

# overwrite any eventually changed configuration
source $TACP_SCRIPT_DIR/running.conf

bridgeInterface="$tacPlusInterface.$tacPlusInterfaceVlan"
bridgeName="$tacPlusBridgeName"

#detach_bridge_interface
bridge_interface detach $bridgeInterface $bridgeName
compose_down $SERVICE_LIBRARY
rm_running_config
