#!/usr/bin/env bash

#client_ip="172.16.0.4"
#file_name="detail-$(date +%Y%m%d)"

#sudo tail -n100 ./volumes/log/radacct/$client_ip/$file_name

#cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_-]*$serviceName[a-zA-Z0-9_-]*)
cont_name="tacplus_tac_plus_1"
#echo $cont_name

echo "sudo docker logs $cont_name -f"

sudo docker logs $cont_name -f

exit






SERVICE_LIBRARY="tacplus"

# grab configuration
TACP_SOURCE=${BASH_SOURCE[0]}
TACP_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $TACP_SCRIPT_DIR/../functions.sh

cd $TACP_SCRIPT_DIR

# overwrite any eventually changed configuration
source $TACP_SCRIPT_DIR/running.conf

#detach_bridge_interface
compose_down $SERVICE_LIBRARY
rm_running_config
