#!/bin/bash

ipAddr=$1
ifId=$2
ifIndex="100000$2"

echo "snmpwalk -v 2c -c public $ipAddr iso.3.6.1.2.1.1.1"
snmpwalk -v 2c -c public $ipAddr iso.3.6.1.2.1.1.1
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.2.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.2.$ifIndex
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.6.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.6.$ifIndex
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.8.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.8.$ifIndex
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.31.1.1.1.10.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.31.1.1.1.10.$ifIndex
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.31.1.1.1.6.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.31.1.1.1.6.$ifIndex
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.14.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.2.2.1.14.$ifIndex
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.47.1.1.1.1.7.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.47.1.1.1.1.7.$ifIndex
echo ""
echo "snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.31.1.1.1.18.$ifIndex"
snmpget -v 2c -c public $ipAddr 1.3.6.1.2.1.31.1.1.1.18.$ifIndex
