#!/usr/bin/env bash

[ $DEBUG = true ] && echo "Calling: ${BASH_SOURCE[0]}"

speedtest_library()
{
  # set interface type
  if [ $speedtestInterfaceVlan = "0" ]; then
    speedtestIf="$speedtestInterface"
    isVlanIf="false"
  else
    speedtestIf="$speedtestInterface.$speedtestInterfaceVlan"
    isVlanIf="true"
  fi

  # adds a physical interface to the radius bridge (for external reachability)
  attach_bridge_interface()
  {
    # create vlan interface, if necessary 
    if [ $(sudo ip link show | grep "$speedtestIf" | wc -l) -lt 1 ]; then
      if [ $isVlanIf = "true" ]; then
        ipv4_to_lamac $speedtestIpAddress
        create_vlan_interface $speedtestIf
      fi
    fi

    if [ $(sudo brctl show $speedtestBridgeName |grep $speedtestIf |wc -l) -gt 0 ]; then
      echo "Interface $speedtestIf already assigned to bridge, nothing to do"
      sudo brctl show $speedtestBridgeName |grep $speedtestIf
      return
    elif [ $(sudo brctl show | grep $speedtestIf |wc -l) -gt 0 ]; then
      echo "Interface $speedtestIf assigned to another bridge, please remove interface first"
      return
    fi

    sudo ip link set dev $speedtestIf master $speedtestBridgeName
  }

  detach_bridge_interface()
  {
    if [ $(sudo brctl show $speedtestBridgeName |grep $speedtestIf |wc -l) -gt 0 ]; then
      sudo ip link set dev $speedtestIf nomaster
    fi

    [ $isVlanIf = "true" ] && delete_vlan_interface $speedtestIf
  }

  build_compose_file()
  {
    stBS=$(echo $speedtestBridgeSubnet | sed -e "s.\/.\\\/.g")
    #echo $sttBS
    cat $composeSampleFile | \
    sed -e "s/\$speedtestBridgeName/$speedtestBridgeName/g" \
      -e "s/\$speedtestIpAddress/$speedtestIpAddress/g" \
      -e "s/\$speedtestBridgeSubnet/$stBS/g" > $composeDestFile
    #cat $temp_yaml_file
  }

  remove_running_conf_file()
  {
    # remove old file
    if [ -e $ST_SCRIPT_DIR/running.conf ]; then
      sudo chmod +w $ST_SCRIPT_DIR/running.conf
      rm -f $ST_SCRIPT_DIR/running.conf
    fi
  }

  write_running_config()
  {
    remove_running_conf_file

    echo "# RUNNING CONFIGURATION, DO NOT EDIT THIS FILE!!!" > $ST_SCRIPT_DIR/running.conf
    cat $FUNC_LIB_SCRIPT_DIR/ancillary.conf >> $ST_SCRIPT_DIR/running.conf

    # make it read-only
    sudo chmod 444 $ST_SCRIPT_DIR/running.conf
  }

  clean_up_directory()
  {
    echo "Deleting dynamic configuration files"
    sudo rm -r $ST_SCRIPT_DIR/config/
  }

}

