#!/usr/bin/env bash

SERVICE_LIBRARY="aaa"

# grab configuration
AAA_SOURCE=${BASH_SOURCE[0]}
AAA_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $AAA_SCRIPT_DIR/../functions.sh

cd $AAA_SCRIPT_DIR

# overwrite any eventually changed configuration
source $AAA_SCRIPT_DIR/running.conf

detach_bridge_interface
aaa_down
#sudo docker-compose -p radius -f compose.yaml down
