#!/usr/bin/env bash

element=$1

if [ $element == "all" ];then
  element=aaa1
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  sudo docker exec -it $cont_name /bin/ash -c "radiusd"

  element=aaa2
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  sudo docker exec -it $cont_name /bin/ash -c "radiusd"
else
  cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_]*$element[a-zA-Z0-9_]*)
  
  # reload radius configuration
  sudo docker exec -it $cont_name /bin/ash -c "radiusd"
  
  # show protocol configuration
  #sudo docker exec -it bird_rg_1 /bin/ash -c "birdc show protocol all"
fi
