#!/usr/bin/env bash

#!/usr/bin/env bash

#client_ip="172.16.0.4"
#file_name="detail-$(date +%Y%m%d)"

#sudo tail -n100 ./volumes/log/radacct/$client_ip/$file_name

cont_name=$(sudo docker ps -a |grep -o [a-zA-Z0-9_-]*$1[a-zA-Z0-9_-]*)
#echo $cont_name

sudo docker logs $cont_name -f

