#!/usr/bin/env bash

SERVICE_LIBRARY="aaa"

# grab configuration
AAA_SOURCE=${BASH_SOURCE[0]}
AAA_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#source $AAA_SCRIPT_DIR/../ancillary.conf
. $AAA_SCRIPT_DIR/../functions.sh

cd $AAA_SCRIPT_DIR

composeSampleFile="$AAA_SCRIPT_DIR/compose_sample.yaml"
composeDestFile="$AAA_SCRIPT_DIR/compose.yaml"

#echo "Src $composeSampleFile Dst $composeDestFile"

build_compose_file
compose_up $SERVICE_LIBRARY 
attach_bridge_interface
write_running_config
