#!/usr/bin/env bash

SERVICE_LIBRARY="bgp"
#DEBUG=true

# grab configuration
BGP_SOURCE=${BASH_SOURCE[0]}
BGP_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. $BGP_SCRIPT_DIR/../functions.sh

cd $BGP_SCRIPT_DIR

composeSampleFile="$BGP_SCRIPT_DIR/compose_sample.yaml"
composeDestFile="$BGP_SCRIPT_DIR/compose.yaml"

build_compose_file
compose_up $SERVICE_LIBRARY 
attach_bridge_interface
write_running_config
